// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkBUqQEWLyRdvOzOVhPaqYUrzblyX0NcY',
    appId: '1:605636900000:android:f1f3a85703c471ab51c5c5',
    messagingSenderId: '605636900000',
    projectId: 'ikokas-8f5b2',
    storageBucket: 'ikokas-8f5b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL58IW0Zd2h0IJ0ynl6v5II579JUQsmT8',
    appId: '1:605636900000:ios:4a81ccd45d3df5d451c5c5',
    messagingSenderId: '605636900000',
    projectId: 'ikokas-8f5b2',
    storageBucket: 'ikokas-8f5b2.appspot.com',
    androidClientId: '605636900000-jf5hnng7jq087n6q15iof8rqd741m9b7.apps.googleusercontent.com',
    iosClientId: '605636900000-bfqi06tdub3ld1h32et91aljs0a6apaq.apps.googleusercontent.com',
    iosBundleId: 'com.nitin.ikokas',
  );
}
